site_name: 47byw的学习之路
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_truly_sane_lists
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

nav:
    - 简介: 'index.md'
    - 代码:
      - 《敏捷技能修炼》: 'code/敏捷技能修炼.md'
    - 数据库:
      - 《mysql必知必会》: 'database/mysql必知必会.md'
